#!/usr/bin/env perl

use strict;
use warnings 'FATAL';

use Test::More tests => 3;

use TenxTestEnv;

subtest 'Tenx' => sub {
    plan tests => 2;

    my ($in_inc) = grep { /Tenx\.pm/ } keys %INC;
    ok($in_inc, 'Tenx is in INC');

    my $repo_path = TenxTestEnv::repo_path;
    is($INC{$in_inc}, $repo_path->subdir('lib', 'Tenx.pm'), 'Tenx path is correct');

};

subtest 'ENVs' => sub{
    plan tests => 2;

    ok($ENV{UR_DBI_NO_COMMIT}, 'no commit is on');
    ok($ENV{UR_USE_DUMMY_AUTOGENERATED_IDS}, 'use dummy ids is on');

};

subtest 'test config' => sub{
    plan tests => 3;

    my $test_data_directory = TenxTestEnv::test_data_directory();
    my %expected_configs = (
        tenx_ds => 'Tenx::DataSource::SQLite',
        tenx_ds_sqlite_server => $test_data_directory->subdir('test.db'),
        environment => 'test',
    );
    for my $config_key ( sort keys %expected_configs ) {
        is(Tenx::Config::get($config_key), $expected_configs{$config_key}, $config_key);
    }

};

done_testing();
